# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/showcase/v1/showcase.proto

require 'google/protobuf'

require 'google/longrunning/operations_pb'
require 'google/protobuf/duration_pb'
require 'google/protobuf/empty_pb'
require 'google/protobuf/timestamp_pb'
require 'google/rpc/status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.showcase.v1.EchoRequest" do
    oneof :response do
      optional :content, :string, 1
      optional :error, :message, 2, "google.rpc.Status"
    end
  end
  add_message "google.showcase.v1.EchoResponse" do
    optional :content, :string, 1
  end
  add_message "google.showcase.v1.ExpandRequest" do
    optional :content, :string, 1
    optional :error, :message, 2, "google.rpc.Status"
  end
  add_message "google.showcase.v1.TimeoutRequest" do
    optional :response_delay, :message, 1, "google.protobuf.Duration"
    oneof :response do
      optional :error, :message, 2, "google.rpc.Status"
      optional :success, :message, 3, "google.showcase.v1.TimeoutResponse"
    end
  end
  add_message "google.showcase.v1.TimeoutResponse" do
    optional :content, :string, 1
  end
  add_message "google.showcase.v1.SetupRetryRequest" do
    repeated :responses, :message, 1, "google.rpc.Status"
  end
  add_message "google.showcase.v1.RetryId" do
    optional :id, :string, 1
  end
  add_message "google.showcase.v1.LongrunningRequest" do
    optional :completion_time, :message, 1, "google.protobuf.Timestamp"
    oneof :response do
      optional :error, :message, 2, "google.rpc.Status"
      optional :success, :message, 3, "google.showcase.v1.LongrunningResponse"
    end
  end
  add_message "google.showcase.v1.LongrunningMetadata" do
    optional :time_remaining, :message, 1, "google.protobuf.Duration"
  end
  add_message "google.showcase.v1.LongrunningResponse" do
    optional :content, :string, 1
  end
  add_message "google.showcase.v1.PaginationRequest" do
    optional :max_response, :int32, 1
    optional :page_size, :int32, 2
    optional :page_token, :string, 3
    optional :page_size_override, :int32, 4
  end
  add_message "google.showcase.v1.PaginationResponse" do
    repeated :responses, :int32, 1
    optional :next_page_token, :string, 2
  end
  add_message "google.showcase.v1.ParameterFlatteningMessage" do
    optional :content, :string, 1
    repeated :repeated_content, :string, 2
    optional :nested, :message, 3, "google.showcase.v1.ParameterFlatteningMessage"
  end
  add_message "google.showcase.v1.ResourceNameMessage" do
    optional :single_template, :string, 1
    optional :multiple_templates, :string, 2
  end
end

module Google
  module Showcase
    module V1
      EchoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.EchoRequest").msgclass
      EchoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.EchoResponse").msgclass
      ExpandRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.ExpandRequest").msgclass
      TimeoutRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.TimeoutRequest").msgclass
      TimeoutResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.TimeoutResponse").msgclass
      SetupRetryRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.SetupRetryRequest").msgclass
      RetryId = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.RetryId").msgclass
      LongrunningRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.LongrunningRequest").msgclass
      LongrunningMetadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.LongrunningMetadata").msgclass
      LongrunningResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.LongrunningResponse").msgclass
      PaginationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.PaginationRequest").msgclass
      PaginationResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.PaginationResponse").msgclass
      ParameterFlatteningMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.ParameterFlatteningMessage").msgclass
      ResourceNameMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1.ResourceNameMessage").msgclass
    end
  end
end
